version: '3'

networks:
  zan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  php_zan_http:
    build: ./php/zan
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt/http-demo:/zanphp/http-demo
    working_dir: /zanphp/http-demo
    command: php bin/httpd
    networks:
      zan:
        ipv4_address: 172.30.0.11
    ports:
      - "8030:8030"
    hostname: php_zan_http
    container_name: php_zan_http

  php_zan_tcp:
    build: ./php/zan
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt/tcp-demo:/zanphp/tcp-demo
    working_dir: /zanphp/tcp-demo
    command: php bin/nova
    networks:
      zan:
        ipv4_address: 172.30.0.12
    ports:
      - "8100:8100"
    hostname: php_zan_tcp
    container_name: php_zan_tcp

  mysql_zan:
    build: ./mysql/zan
    volumes:
      - ./opt/mysql/zan/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      zan:
        ipv4_address: 172.30.0.21
    ports:
      - "33061:3306"
    hostname: mysql_zan
    container_name: mysql_zan
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  mysql_cat:
    build: ./mysql/cat
    volumes:
      - ./opt/mysql/cat/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      zan:
        ipv4_address: 172.30.0.22
    ports:
      - "33062:3306"
    hostname: mysql_cat
    container_name: mysql_cat
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  redis_zan:
    build: ./redis/zan
    volumes:
      - ./common/hosts:/etc/hosts:ro
    networks:
      zan:
        ipv4_address: 172.30.0.31
    ports:
      - "63791:6379"
    hostname: redis_zan
    container_name: redis_zan

  etcd_zan:
    build: ./etcd/zan
    volumes:
      - ./common/hosts:/etc/hosts:ro
    networks:
      zan:
        ipv4_address: 172.30.0.41
    ports:
      - "23791:2379"
      - "23801:2380"
    hostname: etcd_zan
    container_name: etcd_zan
